tianguiswatt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER', 'tianguiswatt') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'tianguiswatt') }}"
      schema: "{{ env_var('CLICKHOUSE_DB', 'tianguiswatt') }}"
      secure: false
      threads: 4
